# Generated by Django 6.0.5 on 2026-05-30 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='low_stock_thresold',
            new_name='low_stock_threshold',
        ),
    ]
